/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdvocateComponent: typeof import('./src/components/AdvocateComponent.vue')['default']
    DonateForm: typeof import('./src/components/DonateForm.vue')['default']
    FooterNavbar: typeof import('./src/components/PageHeader/FooterNavbar.vue')['default']
    LatestEvents: typeof import('./src/components/LatestEvents.vue')['default']
    NavbarComponent: typeof import('./src/components/PageHeader/NavbarComponent.vue')['default']
    PageFooter: typeof import('./src/components/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PageSlogan: typeof import('./src/components/PageSlogan.vue')['default']
    PolicyIssues: typeof import('./src/components/PolicyIssues.vue')['default']
    SectionTitle: typeof import('./src/components/utilities/SectionTitle.vue')['default']
  }
}
